version: "3.2"

services:
  backend:
    container_name: ice-project-backend
    restart: always
    environment:
      SERVER_URL:
      LIFF_SERVER_URL:
      ADMIN_SERVER_URL:
      MYSQL_SERVER: db
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
      CHANNEL_ID:
      CHANNEL_SECRET:
      CHANNEL_ACCESS_TOKEN:
      IOT_DEVICE_SECRET:
      LINE_BOT_CHANNEL_TOKEN:
      LINE_MESSAGING_API_ENDPOINT:
    depends_on:
      - db
  grafana:
    container_name: ice-project-grafana
    image: grafana/grafana
    environment: 
      GF_INSTALL_PLUGINS: grafana-worldmap-panel, grafana-piechart-panel, grafana-clock-panel, satellogic-3d-globe-panel
    volumes: 
      - grafana-data:/var/lib/grafana
  db:
    image: mysql:5.7
    container_name: ice-project-db
    restart: always
    volumes:
      - ./volumes/database:/var/lib/mysql
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:

volumes:
  grafana-data:
