version: 2
jobs:
  build_backend:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ checksum "backend/package.json" }}
      - run:
          name: Install dependencies
          command: cd backend && yarn
      - save_cache:
          key: build-cache-{{ checksum "backend/package.json" }}
          paths:
            - ./backend/node_modules
      - run:
          name: Run build
          command: cd backend && yarn build
  lint_backend:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: lint-cache-{{ checksum "backend/package.json" }}
      - run:
          name: Install dependencies
          command: cd backend && yarn
      - save_cache:
          key: lint-cache-{{ checksum "backend/package.json" }}
          paths:
            - ./backend/node_modules
      - run:
          name: Lint
          command: cd backend && yarn lint
  test_backend_e2e:
    docker:
      - image: circleci/node:10
        environment:
          MYSQL_SERVER: db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: db
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        name: db
    steps:
      - checkout
      - restore_cache:
          key: test-cache-{{ checksum "backend/package.json" }}
      - run:
          name: Install dependencies
          command: cd backend && yarn
      - save_cache:
          key: test-cache-{{ checksum "backend/package.json" }}
          paths:
            - ./backend/node_modules
      - run:
          name: Test e2e
          command: cd backend && yarn test:e2e
  test_frontend:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/package.json" }}
      - run:
          name: Install dependencies
          command: cd frontend && npm Install
      - save_cache:
          key: dependency-cache-{{ checksum "frontend/package.json "}}
      - run:
          name: Run tests
          command: cd frontend && npm test
  build_frontend:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/package.json" }}
      - run:
          name: Install dependencies
          command: cd frontend && npm Install
      - save_cache:
          key: dependency-cache-{{ checksum "frontend/package.json "}}
      - run:
          name: Build project
          command: cd frontend && npm run build

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test_frontend
      - build_frontend:
          requires:
            - test_frontend
